/*
 *
 * Mohtv constants
 *
 */

export const DEFAULT_ACTION = 'app/Mohtv/DEFAULT_ACTION';

export const GET_ALL_SHOWS = 'app/Mohtv/GET_ALL_SHOWS';
export const GET_ALL_SHOWS_FAIL = 'app/Mohtv/GET_ALL_SHOWS_FAIL';
export const GET_ALL_SHOWS_SUCCESS = 'app/Mohtv/GET_ALL_SHOWS_SUCCESS';

export const GET_CATEGORY_SHOWS = 'app/Mohtv/GET_CATEGORY_SHOWS';
export const GET_CATEGORY_SHOWS_FAIL = 'app/Mohtv/GET_CATEGORY_SHOWS_FAIL';
export const GET_CATEGORY_SHOWS_SUCCESS = 'app/Mohtv/GET_CATEGORY_SHOWS_SUCCESS';

export const GET_SUB_CATEGORY_SHOWS = 'app/Mohtv/GET_SUB_CATEGORY_SHOWS';
export const GET_SUB_CATEGORY_SHOWS_FAIL = 'app/Mohtv/GET_SUB_CATEGORY_SHOWS_FAIL';
export const GET_SUB_CATEGORY_SHOWS_SUCCESS = 'app/Mohtv/GET_SUB_CATEGORY_SHOWS_SUCCESS';

export const GET_MOHTV_CATEGORIES = 'app/Mohtv/GET_MOHTV_CATEGORIES';
export const GET_MOHTV_CATEGORIES_SUCCESS = 'app/Mohtv/GET_MOHTV_CATEGORIES_SUCCESS';
export const GET_MOHTV_CATEGORIES_FAIL = 'app/Mohtv/GET_MOHTV_CATEGORIES_FAIL';

export const GET_SEARCH_SUGGESTION = 'app/Mohtv/GET_SEARCH_SUGGESTION';
export const GET_SEARCH_SUGGESTION_SUCCESS = 'app/Mohtv/GET_SEARCH_SUGGESTION_SUCCESS';
export const GET_SEARCH_SUGGESTION_FAIL = 'app/Mohtv/GET_SEARCH_SUGGESTION_FAIL';

export const GET_SEARCH_RESULT = 'app/Mohtv/GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_SUCCESS = 'app/Mohtv/GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAIL = 'app/Mohtv/GET_SEARCH_RESULT_FAIL';

export const CLEAR_SUGGESTION = 'app/Mohtv/CLEAR_SUGGESTION';
