export const data = {
  meta_title: 'New title',
  meta_description: 'New description',
  title: 'This is title This is title',
  description: 'This is description This is description This is description This is description This is description',
  banner_mobile: '/static/images/banner1_web.webp',
  banner_desktop: '/static/images/banner1_web.webp',
  about: {
    title: 'Heading',
    description: '<div>This is description</div>',
    read_more: '<div>This is read more</div>',
    image_desktop: '/static/images/delete1.png',
    image_mobile: '/static/images/delete1.png',
    is_visible_on_website: true,
  },
  causes: {
    title: 'Dementia Causes',
    description: '<div>This is description</div>',
    points: [
      { id: '234', title: 'sdfgsfdsfsdf sf ds fds dsf dsfdsfsd sd fdsf ' },
      { id: '2344', title: 'sffdsfdsfsfs fsds fdsf ds fds fdsf sasdasdadadasd' },
      { id: '23442', title: 'sffdsfdsfsfs fsds fdsf ds fds fdsf s' },
      { id: '23443', title: 'sffdsfdsfsfs fsds fdsf ds fds fdsf s' },
      { id: '234445', title: 'sffdsfdsfsfs fsds fdsf ds fds fdsf s' },
      { id: '23444444', title: 'sffdsfdsfsfs fsds fdsf ds fds fdsf s' },
    ],
    is_visible_on_website: true,
  },
  symptoms: {
    title: 'Symptoms of Dementia',
    description: '<div>This is description</div>',
    image_desktop: '/static/images/delete1.png',
    image_mobile: '/static/images/delete1.png',
    is_visible_on_website: true,
    points: [
      {
        id: '12',
        title: 'qwefsfsdf sdfsdfsd fs fdfs dsf s s s dsf ',
        icon_desktop: '/static/images/expand_more_black.webp',
        icon_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: '23',
        title: 'sdfadsfdsfdsfdsf  adsfsfdsfdsf ds s ds dsf sd fds fs',
        icon_desktop: '/static/images/expand_more_black.webp',
        icon_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: '234',
        title: 'sdfadsfdsfdsfdsf  adsfsfdsfdsf ds s ds dsf sd fds fs',
        icon_desktop: '/static/images/expand_more_black.webp',
        icon_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: '23dfsg',
        title: 'sdfadsfdsfdsfdsf  adsfsfdsfdsf ds s ds dsf sd fds fs',
        icon_desktop: '/static/images/expand_more_black.webp',
        icon_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: '23sdf',
        title: 'sdfadsfdsfdsfdsf  adsfsfdsfdsf ds s ds dsf sd fds fs',
        icon_desktop: '/static/images/expand_more_black.webp',
        icon_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: '23fgh',
        title: 'sdfadsfdsfdsfdsf  adsfsfdsfdsf ds s ds dsf sd fds fs',
        icon_desktop: '/static/images/expand_more_black.webp',
        icon_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: '23bcnv',
        title: 'sdfadsfdsfdsfdsf  adsfsfdsfdsf ds s ds dsf sd fds fs',
        icon_desktop: '/static/images/expand_more_black.webp',
        icon_mobile: '/static/images/expand_more_black.webp',
      },
    ],
  },
  care: {
    title: 'Dementia Care & Treatment',
    description: 'Key components of Dementia Care',
    points: [
      {
        id: 'dsfdsf',
        title: 'adsfg',
        description: 'sdfsdfdsf',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'sdfsadf',
        title: 'sadfsffdsfs',
        description: 'sdfadsfdsfsdfadsf',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'dsfdsf',
        title: 'adsfg',
        description: 'sdfsdfdsf',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'sdfsadf',
        title: 'sadfsffdsfs',
        description: 'sdfadsfdsfsdfadsf',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'dsfdsf',
        title: 'adsfg',
        description: 'sdfsdfdsf',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'sdfsadf',
        title: 'sadfsffdsfs',
        description: 'sdfadsfdsfsdfadsf',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
    ],
    is_visible_on_website: true,
  },
  second_banner: {
    title: 'dsfdsfadsfs',
    description: ' sdfsdf sd ds sfs sdf sd fs dsf ds fsdf dsf ds ss sf dsf ds ds dsf ',
    banner_mobile: '/static/images/expand_more_black.webp',
    banner_desktop: '/static/images/expand_more_black.webp',
    is_visible_on_website: true,
  },
  customized_care_plan: {
    title: 'Care plan',
    is_visible_on_website: true,
    points: [
      {
        id: 'asdasd asd a ad',
        title: 'asdfad',
        description: 'adadada asdfdfs',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'adasd',
        title: 'adada',
        description: 'asdasdasdasd asd asdad',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'asdasd asd a ad',
        title: 'asdfad',
        description: 'adadada',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'adasd',
        title: 'adada',
        description: 'asdasdasdasd asd asdad',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'asdasd asd a ad',
        title: 'asdfad',
        description: 'adadada',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'adasd',
        title: 'adada',
        description: 'asdasdasdasd asd asdad',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'asdasd asd a ad',
        title: 'asdfad',
        description: 'adadada',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'adasd',
        title: 'adada',
        description: 'asdasdasdasd asd asdad',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
      {
        id: 'adasd',
        title: 'adada',
        description: 'asdasdasdasd asd asdad',
        image_desktop: '/static/images/expand_more_black.webp',
        image_mobile: '/static/images/expand_more_black.webp',
      },
    ],
  },
  expert_list: {
    title: 'Expert list',
    is_visible_on_website: true,
    points: [
      {
        id: 'asd',
        title: 'asdasd',
        description: 'adasdasdas',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: 'asdasdasasd',
        title: 'adasdasd asda da',
        description: 'a da da a as dasd ',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: 'a sdas a a da da',
        title: ' asdasd as das d',
        description: ' asdasdas das',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: 'a asdasdasd as as a dsa',
        title: 'a sdadasdasd as das ',
        description: ' asdad as dad a ad asd',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: 'dasd asd ad asdasd ',
        title: ' asdadasd as a dasdasd',
        description: 'as dadasdasdas d',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: 'adsasdasd  a sd',
        title: 'as dadas as dad a dasd',
        description: 'adasd ad a as dasd asd',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
    ],
  },
  ratings: [
    {
      name: 'asdasd',
      comment: 'asdasdasd ads a da ad as ad as das a sddas asd asd asd as ad das asd as a das das  d as dasd as a sd',
      rating: 3,
    },
    {
      name: 'asdasd as as da',
      comment: ' asdas das asd as das a das das das asd as asd as asd ',
      rating: 4,
    },
  ],
  blogs: {
    view_all_navigation: 'slug',
    is_visible_on_website: true,
    data: [
      'https://emoha.com/blogs/fitness/the-impressive-story-of-winning-medals-in-athletics-at-the-age-of-94',
      'https://emoha.com/blogs/health/simple-and-effective-natural-home-remedies-for-pneumonia',
      'https://emoha.com/blogs/health/is-there-a-difference-between-bb-cc-and-dd-creams-when-should-we-use-them',
    ],
  },
  mohtv_shows: {
    is_visible_on_website: true,
    mohtv_category_name: '',
    mohtv_category_uuid: '',
    mohtv_sub_category_name: '',
    mohtv_sub_category_uuid: '',
    mohtv_sub_category_shows: [
      {
        id: '',
        meeting_topic: 'Geet Mala',
        event_meeting_uuid: '81e8b55e-1b07-451b-a5b3-f21a442b6699',
        meeting_details_uuid: '87a8b716-5795-4ccd-8db1-02166d0373cc',
      },
      {
        id: '',
        meeting_topic: 'Geet Mala',
        event_meeting_uuid: '81e8b55e-1b07-451b-a5b3-f21a442b6699',
        meeting_details_uuid: '87a8b716-5795-4ccd-8db1-02166d0373cc',
      },
    ],
  },
  faqs: [
    { id: 'adasd', question: 'adefdsfgdsf', answer: ' sadf dfs fdsf ds dsf sd f' },
    { id: 'asdasd', question: ' sdfsd fdsf dfs sd f', answer: ' sdfsd fsd fsd f' },
    { id: 'adasd', question: 'adefdsfgdsf', answer: ' sadf dfs fdsf ds dsf sd f' },
    { id: 'asdasd', question: ' sdfsd fdsf dfs sd f', answer: ' sdfsd fsd fsd f' },
    { id: 'adasd', question: 'adefdsfgdsf', answer: ' sadf dfs fdsf ds dsf sd f' },
    { id: 'asdasd', question: ' sdfsd fdsf dfs sd f', answer: ' sdfsd fsd fsd f' },
  ],
  resources: {
    title: 'asdasdaadasd',
    is_visible_on_website: true,
    data: [
      {
        id: '',
        url: '/static/images/expand_more_black.webp',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: '',
        url: '/static/images/expand_more_black.webp',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: '',
        url: '/static/images/expand_more_black.webp',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: '',
        url: '/static/images/expand_more_black.webp',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
      {
        id: '',
        url: '/static/images/expand_more_black.webp',
        image_desktop: '/static/images/delete1.png',
        image_mobile: '/static/images/delete1.png',
      },
    ],
  },
};
